# Site settings
title: Yen-Liang "Carr" Lin
email: asdfg1436@gmail.com
url: https://asdfg1436.github.io/
description: "I am Yen-Liang Lin, a game programmer from Taiwan. I am currently studying in DigiPen MSCS and my specialization is gameplay and AI."
keywords: "Game Programmer, Gameplay Programmer, AI Programmer"
skills: "Software Engineer - Game Programmer - Gameplay/AI Programmer"
meta_author: Yen-Liang Lin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Yen-Liang "Carr" Lin
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/lin-yen-liang-5a7244158/
  - title: envelope
    url: mailto:asdfg1436@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Seattle WA, United States
  - line: Taichung, Taiwan

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
